travis:
  secure:
    BINSTAR_TOKEN: pIyb2YBODhbV4mMpjqxrfNf2E4rmnQs/skn0L0BAZpPeU9e0wjGm7XIOxxZ4EXWlsLmlcDK+L5K275cR2j/U/FHe+JC9csWJ0MmH/+uz5uaD16+YF7QIopLimvzDLAMR/39hX9n/uECgAjADrEBjz63eVwh/MEiaqj3sTsWTzTgmJU0RQHM0/mDbrSW+wyUE+a/idTtn6p0hIMy49+IExbDLd44lTGXtxbkUFO7tY3fj+ilVXSEuozxmcK33DerFeh/gljVt9KzS6iEuBBt7kINiha62g5a+/nq4rPIR2mTi5YhOFOVwWWqQKH+Kc8sCL6mX5nCNzz4mMiskM3LFLdaj7c2CnrucZL0LWQWoKjk+4qxpZeglqRRUAwX+VFRlhg7GB/9HalsdPAYqwHDcclvu0CxqGWP2h4/O3j308VGBE2PeLq+9WH+9wQDfz4T6Ax4X9fmvlXrVls0KGYpR9kXtcmedzriJMGq9dyjXJC0oMsgZLSZauZ1LezDEybMnuMI9kw+34p5p7UOrXBQ35M5YvySUakStQGoAxMjoK49TSGszC2ZPuFKBGmGQ82UzgLuTS897yYKwE57AwqFoUj3YhW5CeN32b2NYzjo/hfPTQLxNBJnU3lhRQfctg+r8UzlTnZuzzTLCkTmjaSp4FR6r30VE4ZlJmLvjIZuQWmI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
